try {
    let a = 10
}catch(err){
    console.error("a")
}
console.error("a")